repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.1.1'
    hooks:  # Related: https://stackoverflow.com/a/75003826/3858494
      - id: mypy
        name: mypy (python)
        require_serial: true
        language: system
        types: [python]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.255'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        name: isort (python)
